<a href="https://colab.research.google.com/github/arun4589/ML/blob/main/CNN_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.datasets import mnist

In [2]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [3]:
from tensorflow.keras.utils import to_categorical
print(y_train[:10])
y_train=to_categorical(y_train,10)
y_test=to_categorical(y_test,10)
print(y_train[:10])

[5 0 4 1 9 2 1 3 1 4]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [4]:
## above we have one hot encoded our outputs (total outputs are 10 so first we printed initial 10 outputs in y_train and then we printed their onr hot encoded form)

In [5]:
x_train.shape[0]

60000

In [6]:
row , col = 28,28
x_train=x_train.reshape(x_train.shape[0],row,col,1)
x_test=x_test.reshape(x_test.shape[0],row,col,1)
input_shape=(row,col,1)



In [7]:
## now we will do the most important part of CNN : THE ARCHITECTURE
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D,MaxPooling2D,Flatten, Dropout
# build model object
model = Sequential()
# convolution layer with relu activation and depth=32 kernals
model.add(Conv2D(32,kernel_size=(3,3),padding ="same",activation='relu',input_shape=(28,28,1))) # after this image become 32*28*28
# max pooling layer => downsample the image to chose best features
model.add(MaxPooling2D(pool_size=(2,2))) # after this image = 32*14*14
# adding another conv layer to increas depth=64
model.add(Conv2D(64,kernel_size=(3,3),padding ="same",activation='relu')) # image=64*14*14
# adding pooling layer
model.add(MaxPooling2D(pool_size=(2,2))) # image=64*7*7
## we have completed the convolution part now the rest process remain same as ANN
model.add(Flatten()) # image=64*49=3136(total input to first hidden layer)
model.add(Dense( 64, activation='relu'))# hidden layer1
model.add(Dense(10,activation='softmax')) #output layer
model.summary()


/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 28, 28, 32)          │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 14, 14, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 14, 14, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 7, 7, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 3136)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 64)                  │         200,768 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 220,234 (860.29 KB)

 Trainable params: 220,234 (860.29 KB)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [9]:
from tensorflow.keras.callbacks import ModelCheckpoint
checkpoint = ModelCheckpoint("mnist.keras",verbose=1,save_best_only=True)
hist=model.fit(x_train,y_train,batch_size=64,epochs=20,validation_data=(x_test,y_test),callbacks=[checkpoint],verbose=2,shuffle=True)

Epoch 1/20

Epoch 1: val_loss improved from inf to 0.05695, saving model to mnist.keras
938/938 - 12s - 12ms/step - accuracy: 0.9465 - loss: 0.4218 - val_accuracy: 0.9818 - val_loss: 0.0569
Epoch 2/20

Epoch 2: val_loss did not improve from 0.05695
938/938 - 2s - 2ms/step - accuracy: 0.9826 - loss: 0.0612 - val_accuracy: 0.9787 - val_loss: 0.0735
Epoch 3/20

Epoch 3: val_loss did not improve from 0.05695
938/938 - 3s - 3ms/step - accuracy: 0.9877 - loss: 0.0415 - val_accuracy: 0.9806 - val_loss: 0.0766
Epoch 4/20

Epoch 4: val_loss did not improve from 0.05695
938/938 - 3s - 3ms/step - accuracy: 0.9905 - loss: 0.0344 - val_accuracy: 0.9826 - val_loss: 0.0786
Epoch 5/20

Epoch 5: val_loss improved from 0.05695 to 0.05245, saving model to mnist.keras
938/938 - 2s - 3ms/step - accuracy: 0.9927 - loss: 0.0268 - val_accuracy: 0.9878 - val_loss: 0.0525
Epoch 6/20

Epoch 6: val_loss improved from 0.05245 to 0.04935, saving model to mnist.keras
938/938 - 2s - 3ms/step - accuracy: 0.9930 - loss

In [10]:
score=model.evaluate(x_test,y_test,verbose=0)
print('Test loss:',score[0])
print('Test accuracy:',score[1])

Test loss: 0.20240598917007446
Test accuracy: 0.9850999712944031


NOW we will work with RGB images

In [11]:
import keras
from keras.datasets import cifar10

In [12]:
(x_train,y_train),(x_test,y_test)=cifar10.load_data()

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 6s 0us/step


In [13]:
x_train=x_train.astype('float32')/255.
x_test=x_test.astype('float32')/255.


In [14]:
import numpy as np
from tensorflow.keras.utils import to_categorical
num_classes=len(np.unique(y_train))
print(num_classes)
y_train=to_categorical(y_train,num_classes)
y_test=to_categorical(y_test,num_classes)
(x_train,x_valid)=x_train[5000:],x_train[:5000]
(y_train,y_valid)=y_train[5000:],y_train[:5000]


10


In [15]:
x_train.shape

(45000, 32, 32, 3)

In [16]:
x_test.shape

(10000, 32, 32, 3)

In [17]:
x_valid.shape

(5000, 32, 32, 3)

In [18]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten,Conv2D,MaxPooling2D
model_1=Sequential()
model_1.add(Conv2D(16,kernel_size=3,padding='same',activation='relu',input_shape=(32,32,3))) # we took input size =32*32*3 because we have 3 channels RGB
model_1.add(MaxPooling2D(pool_size=2))
model_1.add(Conv2D(32,kernel_size=3,padding='same',activation='relu'))
model_1.add(MaxPooling2D(pool_size=2))
model_1.add(Conv2D(64,kernel_size=3,padding='same',activation='relu'))
model_1.add(MaxPooling2D(pool_size=2))
model_1.add(Dropout(0.25))
model_1.add(Flatten())
model_1.add(Dense(500,activation='relu'))
model_1.add(Dropout(0.4))
model_1.add(Dense(10,activation='softmax'))
model_1.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_2 (Conv2D)                    │ (None, 32, 32, 16)          │             448 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 16, 16, 16)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 16, 16, 32)          │           4,640 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 8, 8, 32)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 8, 8, 64)            │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 4, 4, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 4, 4, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 1024)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 500)                 │         512,500 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 500)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 10)                  │           5,010 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 541,094 (2.06 MB)

 Trainable params: 541,094 (2.06 MB)

 Non-trainable params: 0 (0.00 B)

In [19]:
model_1.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [20]:
from keras.callbacks import ModelCheckpoint
checkpoint = ModelCheckpoint("cifar10.keras",verbose=1,save_best_only=True)
hist_1=model_1.fit(x_train,y_train,batch_size=32,epochs=20,validation_data=(x_valid,y_valid),callbacks=[checkpoint],verbose=2,shuffle=True)

Epoch 1/20

Epoch 1: val_loss improved from inf to 2.45728, saving model to cifar10.keras
1407/1407 - 9s - 7ms/step - accuracy: 0.4265 - loss: 1.5795 - val_accuracy: 0.2850 - val_loss: 2.4573
Epoch 2/20

Epoch 2: val_loss improved from 2.45728 to 1.13410, saving model to cifar10.keras
1407/1407 - 5s - 4ms/step - accuracy: 0.5688 - loss: 1.2146 - val_accuracy: 0.6026 - val_loss: 1.1341
Epoch 3/20

Epoch 3: val_loss improved from 1.13410 to 1.03351, saving model to cifar10.keras
1407/1407 - 5s - 4ms/step - accuracy: 0.6231 - loss: 1.0766 - val_accuracy: 0.6334 - val_loss: 1.0335
Epoch 4/20

Epoch 4: val_loss improved from 1.03351 to 0.92948, saving model to cifar10.keras
1407/1407 - 4s - 3ms/step - accuracy: 0.6541 - loss: 0.9937 - val_accuracy: 0.6708 - val_loss: 0.9295
Epoch 5/20

Epoch 5: val_loss improved from 0.92948 to 0.86038, saving model to cifar10.keras
1407/1407 - 4s - 3ms/step - accuracy: 0.6745 - loss: 0.9450 - val_accuracy: 0.7036 - val_loss: 0.8604
Epoch 6/20

Epoch 6: val

In [23]:
model_1.load_weights("cifar10.keras")
score=model_1.evaluate(x_test,y_test,verbose=0)
print('Test loss:',score[0])
print('Test accuracy:',score[1])

Test loss: 0.8888445496559143
Test accuracy: 0.6942999958992004
