<a href="https://colab.research.google.com/github/arun4589/ML/blob/main/CNN_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.datasets import mnist

In [2]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [4]:
from tensorflow.keras.utils import to_categorical
print(y_train[:10])
y_train=to_categorical(y_train,10)
y_test=to_categorical(y_test,10)
print(y_train[:10])

[5 0 4 1 9 2 1 3 1 4]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [5]:
## above we have one hot encoded our outputs (total outputs are 10 so first we printed initial 10 outputs in y_train and then we printed their onr hot encoded form)

In [12]:
x_train.shape[0]

60000

In [13]:
row , col = 28,28
x_train=x_train.reshape(x_train.shape[0],row,col,1)
x_test=x_test.reshape(x_test.shape[0],row,col,1)
input_shape=(row,col,1)



In [14]:
## now we will do the most important part of CNN : THE ARCHITECTURE
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D,MaxPooling2D,Flatten, Dropout
# build model object
model = Sequential()
# convolution layer with relu activation and depth=32 kernals
model.add(Conv2D(32,kernel_size=(3,3),padding ="same",activation='relu',input_shape=(28,28,1))) # after this image become 32*28*28
# max pooling layer => downsample the image to chose best features
model.add(MaxPooling2D(pool_size=(2,2))) # after this image = 32*14*14
# adding another conv layer to increas depth=64
model.add(Conv2D(64,kernel_size=(3,3),padding ="same",activation='relu')) # image=64*14*14
# adding pooling layer
model.add(MaxPooling2D(pool_size=(2,2))) # image=64*7*7
## we have completed the convolution part now the rest process remain same as ANN
model.add(Flatten()) # image=64*49=3136(total input to first hidden layer)
model.add(Dense( 64, activation='relu'))# hidden layer1
model.add(Dense(10,activation='softmax')) #output layer
model.summary()


/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 28, 28, 32)          │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 14, 14, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 14, 14, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 7, 7, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 3136)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 64)                  │         200,768 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 220,234 (860.29 KB)

 Trainable params: 220,234 (860.29 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
from tensorflow.keras.callbacks import ModelCheckpoint
checkpoint = ModelCheckpoint("mnist.keras",verbose=1,save_best_only=True)
hist=model.fit(x_train,y_train,batch_size=64,epochs=10,validation_data=(x_test,y_test),callbacks=[checkpoint],verbose=2,shuffle=True)

Epoch 1/10
