<a href="https://colab.research.google.com/github/arun4589/ML/blob/main/decisiontree(ones_again).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_wine
df = load_wine()


In [6]:
dir(df)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [8]:
df.data.shape

(178, 13)

In [9]:
df.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [10]:
x=pd.DataFrame(df.data,columns=df.feature_names)
x.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [11]:
y=pd.DataFrame(df.target,columns=['target'])
y.head()

target
0       0
1       0
2       0
3       0
4       0

In [12]:
# in decision tree we need not to do scaling
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [13]:
x_train.shape

(142, 13)

In [14]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()

In [15]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [16]:
y_pred=model.predict(x_test)

In [17]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[11  0  0]
 [ 2 11  1]
 [ 1  0 10]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88        11
           1       1.00      0.79      0.88        14
           2       0.91      0.91      0.91        11

    accuracy                           0.89        36
   macro avg       0.90      0.90      0.89        36
weighted avg       0.91      0.89      0.89        36

0.8888888888888888


In [21]:
# now we will do hyper parameter tuning
para={
    'criterion':['gini','entropy'],
    'splitter':['best','random'],
    'max_depth':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
}

In [22]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(model,param_grid=para,cv=5)

In [23]:
grid.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/numpy/ma/core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                       13, 14, 15],
                         'splitter': ['best', 'random']})

In [26]:
grid.best_params_

{'criterion': 'entropy', 'max_depth': 15, 'splitter': 'best'}

In [24]:
y_grid=grid.predict(x_test)

In [25]:
print(confusion_matrix(y_test,y_grid))
print(classification_report(y_test,y_grid))
print(accuracy_score(y_test,y_grid))

[[11  0  0]
 [ 2 12  0]
 [ 1  0 10]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88        11
           1       1.00      0.86      0.92        14
           2       1.00      0.91      0.95        11

    accuracy                           0.92        36
   macro avg       0.93      0.92      0.92        36
weighted avg       0.93      0.92      0.92        36

0.9166666666666666


In [ ]:
# we can see that accuracy is increased after applying gridsearch cv