In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [2]:
X,y=load_iris(return_X_y=True)

In [3]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
   X, y, test_size=0.3, random_state=0)

In [13]:
from sklearn.naive_bayes import GaussianNB

In [14]:
gauss=GaussianNB()

In [15]:
gauss.fit(X_train,y_train)

GaussianNB()

In [16]:
y_pred=gauss.predict(X_test)

In [17]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


Example

In [18]:
import seaborn as sns

In [20]:
df=sns.load_dataset('tips')
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [23]:
from sklearn.preprocessing import OneHotEncoder

In [27]:
encode=OneHotEncoder()

In [29]:
encode.fit_transform(df[['sex','smoker','day']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 732 stored elements and shape (244, 8)>

In [32]:
en_df=pd.DataFrame(encode.fit_transform(df[['sex','smoker','day']]).toarray(),columns=encode.get_feature_names_out())

In [33]:
en_df

sex_Female  sex_Male  smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  \
0           1.0       0.0        1.0         0.0      0.0      0.0      1.0   
1           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
2           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
3           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
4           1.0       0.0        1.0         0.0      0.0      0.0      1.0   
..          ...       ...        ...         ...      ...      ...      ...   
239         0.0       1.0        1.0         0.0      0.0      1.0      0.0   
240         1.0       0.0        0.0         1.0      0.0      1.0      0.0   
241         0.0       1.0        0.0         1.0      0.0      1.0      0.0   
242         0.0       1.0        1.0         0.0      0.0      1.0      0.0   
243         1.0       0.0        1.0         0.0      0.0      0.0      0.0   

     day_Thur  
0         0.0  
1         0.0  
2         0.0  
3         0.0  
4         0.0  
..        ...  
239       0.0  
240       0.0  
241       0.0  
242       0.0  
243       1.0  

[244 rows x 8 columns]

In [36]:
merge=pd.concat([df,en_df],axis=1)

In [37]:
merge

total_bill   tip     sex smoker   day    time  size  sex_Female  \
0         16.99  1.01  Female     No   Sun  Dinner     2         1.0   
1         10.34  1.66    Male     No   Sun  Dinner     3         0.0   
2         21.01  3.50    Male     No   Sun  Dinner     3         0.0   
3         23.68  3.31    Male     No   Sun  Dinner     2         0.0   
4         24.59  3.61  Female     No   Sun  Dinner     4         1.0   
..          ...   ...     ...    ...   ...     ...   ...         ...   
239       29.03  5.92    Male     No   Sat  Dinner     3         0.0   
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1.0   
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0.0   
242       17.82  1.75    Male     No   Sat  Dinner     2         0.0   
243       18.78  3.00  Female     No  Thur  Dinner     2         1.0   

     sex_Male  smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  day_Thur  
0         0.0        1.0         0.0      0.0      0.0      1.0       0.0  
1         1.0        1.0         0.0      0.0      0.0      1.0       0.0  
2         1.0        1.0         0.0      0.0      0.0      1.0       0.0  
3         1.0        1.0         0.0      0.0      0.0      1.0       0.0  
4         0.0        1.0         0.0      0.0      0.0      1.0       0.0  
..        ...        ...         ...      ...      ...      ...       ...  
239       1.0        1.0         0.0      0.0      1.0      0.0       0.0  
240       0.0        0.0         1.0      0.0      1.0      0.0       0.0  
241       1.0        0.0         1.0      0.0      1.0      0.0       0.0  
242       1.0        1.0         0.0      0.0      1.0      0.0       0.0  
243       0.0        1.0         0.0      0.0      0.0      0.0       1.0  

[244 rows x 15 columns]

In [44]:
X=merge.drop(['sex','smoker','day','time'],axis=1)

In [45]:
X

total_bill   tip  size  sex_Female  sex_Male  smoker_No  smoker_Yes  \
0         16.99  1.01     2         1.0       0.0        1.0         0.0   
1         10.34  1.66     3         0.0       1.0        1.0         0.0   
2         21.01  3.50     3         0.0       1.0        1.0         0.0   
3         23.68  3.31     2         0.0       1.0        1.0         0.0   
4         24.59  3.61     4         1.0       0.0        1.0         0.0   
..          ...   ...   ...         ...       ...        ...         ...   
239       29.03  5.92     3         0.0       1.0        1.0         0.0   
240       27.18  2.00     2         1.0       0.0        0.0         1.0   
241       22.67  2.00     2         0.0       1.0        0.0         1.0   
242       17.82  1.75     2         0.0       1.0        1.0         0.0   
243       18.78  3.00     2         1.0       0.0        1.0         0.0   

     day_Fri  day_Sat  day_Sun  day_Thur  
0        0.0      0.0      1.0       0.0  
1        0.0      0.0      1.0       0.0  
2        0.0      0.0      1.0       0.0  
3        0.0      0.0      1.0       0.0  
4        0.0      0.0      1.0       0.0  
..       ...      ...      ...       ...  
239      0.0      1.0      0.0       0.0  
240      0.0      1.0      0.0       0.0  
241      0.0      1.0      0.0       0.0  
242      0.0      1.0      0.0       0.0  
243      0.0      0.0      0.0       1.0  

[244 rows x 11 columns]

In [47]:
y=df.time

In [53]:
X_train, X_test, y_train, y_test = train_test_split(
   X, y, test_size=0.33, random_state=42)

In [54]:
gaus=GaussianNB()

In [55]:
gaus.fit(X_train,y_train)

GaussianNB()

In [56]:
y_pred=gaus.predict(X_test)
y_pred

array(['Dinner', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Lunch',
       'Lunch', 'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Lunch', 'Dinner',
       'Lunch', 'Lunch', 'Lunch', 'Dinner', 'Dinner', 'Lunch', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Dinner',
       'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Dinner',
       'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Lunch',
       'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Lunch', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Lunch', 'Lunch'], dtype='<U6')

In [57]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9629629629629629
              precision    recall  f1-score   support

      Dinner       1.00      0.95      0.97        60
       Lunch       0.88      1.00      0.93        21

    accuracy                           0.96        81
   macro avg       0.94      0.97      0.95        81
weighted avg       0.97      0.96      0.96        81

[[57  3]
 [ 0 21]]
