In [1]:
import numpy as np

In [2]:
arr=np.array([2,4,6])

In [3]:
arr

array([2, 4, 6])

In [4]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [5]:
len(dir(np))

530

In [6]:
ar=np.arange(1000)

In [7]:
ar

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [8]:
%time for _ in range(100):[item*3 for item in ar]

CPU times: total: 15.6 ms
Wall time: 18.9 ms


In [9]:
lis=list(range(100))

In [10]:
%time for _ in range(100):[item*3 for item in lis]

CPU times: total: 0 ns
Wall time: 1.02 ms


In [11]:
arra=np.array([[2,5,7],[1,8,3],[2,9,7]])
print(arra)


[[2 5 7]
 [1 8 3]
 [2 9 7]]


In [12]:
arra


array([[2, 5, 7],
       [1, 8, 3],
       [2, 9, 7]])

In [13]:
arra.shape


(3, 3)

In [14]:
arra.dtype

dtype('int64')

In [15]:
array1=np.array([[2.3,4,6,2],[1,4.6,2,8]], dtype='float32')
print(array1)

[[2.3 4.  6.  2. ]
 [1.  4.6 2.  8. ]]


In [16]:
array1=np.array([[2.3,4,6,2],[1,4.6,2,8]], dtype='int64')
print(array1)

[[2 4 6 2]
 [1 4 2 8]]


In [17]:
array1.shape

(2, 4)

In [18]:
array1.dtype

dtype('int64')

In [19]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((2,3)).dtype

dtype('float64')

In [21]:
#operations on array
arra*arra

array([[ 4, 25, 49],
       [ 1, 64,  9],
       [ 4, 81, 49]])

In [22]:
arra+arra

array([[ 4, 10, 14],
       [ 2, 16,  6],
       [ 4, 18, 14]])

In [23]:
arra-arra

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
arra/arra

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
#a raised to power a
arra**arra

array([[        4,      3125,    823543],
       [        1,  16777216,        27],
       [        4, 387420489,    823543]])

In [26]:
1/arra

array([[0.5       , 0.2       , 0.14285714],
       [1.        , 0.125     , 0.33333333],
       [0.5       , 0.11111111, 0.14285714]])

In [27]:
#slicing
df=np.array([2,8,5,3,9,0,3,7,1,5])

In [28]:
df2=df[2:6]
print(df2)

[5 3 9 0]


In [29]:
df2[1]=10
#if we change value in df2 then it reflects on original array

In [30]:
df

array([ 2,  8,  5, 10,  9,  0,  3,  7,  1,  5])

In [31]:
df=np.array([2,8,5,3,9,0,3,7,1,5])

In [32]:
df2=df[2:6].copy()
#using this fun we can eliminate above problem

In [33]:
df2[1]=11

In [34]:
df

array([2, 8, 5, 3, 9, 0, 3, 7, 1, 5])

In [35]:
arra[1,1]

np.int64(8)

In [36]:
print(arra[2,2])

7


In [37]:
ar1=np.array([[2,5,6,1],[8,5,2,6],[1,6,0,3],[1,2,9,3]])
ar1.sum(axis=1)

array([14, 21, 10, 15])

In [38]:
ar1.sum()

np.int64(60)

In [39]:
ar1.sum(axis=0)

array([12, 18, 17, 13])

In [40]:
ar2=np.array([[2,4,6,1],[8,5,2,6],[6,6,0,3],[1,2,1,3]])

In [41]:
ar1.dot(ar2.transpose())

array([[ 61,  59,  45,  21],
       [ 54, 129,  96,  38],
       [ 29,  56,  51,  22],
       [ 67,  54,  27,  23]])

In [42]:
np.cross(arra,arra)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [43]:
np.dot(arra,arra)

array([[ 23, 113,  78],
       [ 16,  96,  52],
       [ 27, 145,  90]])

In [44]:
np.sort(arra)

array([[2, 5, 7],
       [1, 3, 8],
       [2, 7, 9]])

In [45]:
np.sort(ar1,axis=0)

array([[1, 2, 0, 1],
       [1, 5, 2, 3],
       [2, 5, 6, 3],
       [8, 6, 9, 6]])

In [46]:
np.sort(ar1,axis=1,kind='quicksort')

array([[1, 2, 5, 6],
       [2, 5, 6, 8],
       [0, 1, 3, 6],
       [1, 2, 3, 9]])

In [47]:
%%time 
np.sort(ar1,axis=1,kind='quicksort')

CPU times: total: 0 ns
Wall time: 0 ns


array([[1, 2, 5, 6],
       [2, 5, 6, 8],
       [0, 1, 3, 6],
       [1, 2, 3, 9]])

In [54]:
ar3=np.array([1,4,7,9,7,4,2,5,6,9,2,0,3,1,5])
ar4=ar3.reshape(5,3)
ar4

array([[1, 4, 7],
       [9, 7, 4],
       [2, 5, 6],
       [9, 2, 0],
       [3, 1, 5]])

In [55]:
np.argsort(ar3)

array([11,  0, 13,  6, 10, 12,  5,  1, 14,  7,  8,  2,  4,  3,  9])

In [56]:
np.argmin(ar3)

np.int64(11)

In [57]:
np.argmax(ar3)


np.int64(3)

In [58]:
np.argsort(ar4)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 1, 2],
       [2, 1, 0],
       [1, 0, 2]])

In [60]:
np.argsort(ar4,axis=0)

array([[0, 4, 3],
       [2, 3, 1],
       [4, 0, 4],
       [1, 2, 2],
       [3, 1, 0]])