<a href="https://colab.research.google.com/github/arun4589/ML/blob/main/Text_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"amitsippy","key":"2e822b015d7fa9f41dd450352d7f8ebd"}'}

In [3]:
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [4]:
!kaggle datasets download -d lakshmi25npathi/imdb-dataset-of-50k-movie-reviews


Dataset URL: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews
License(s): other
imdb-dataset-of-50k-movie-reviews.zip: Skipping, found more recently modified local copy (use --force to force download)


In [5]:
!unzip imdb-dataset-of-50k-movie-reviews.zip


Archive:  imdb-dataset-of-50k-movie-reviews.zip
replace IMDB Dataset.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: IMDB Dataset.csv        


In [6]:
import pandas as pd

# Load the dataset
df = pd.read_csv('IMDB Dataset.csv')

# Display the first few rows
print(df.head())


                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive


In [7]:

data=df.iloc[:10000]

In [8]:
##this is a classification problem in which we have to classify on the basis of sentiment in review we will apply various ML and DL(word2vec) techniques and see what will work
# first we will preprocess the data(cleaning)
data['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [9]:
data.isnull().sum()

review       0
sentiment    0
dtype: int64

In [10]:
data.duplicated().sum()

17

In [11]:
data.drop_duplicates(inplace=True)

<ipython-input-11-515f69ef7765>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop_duplicates(inplace=True)


In [12]:
data.duplicated().sum()

0

In [13]:
data.shape

(9983, 2)

In [14]:
import re
def remove_tags(text):
  return re.sub(re.compile('<.*?>'),'',text)

In [15]:
data['review']=data['review'].apply(remove_tags)

<ipython-input-15-bde771064b21>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['review']=data['review'].apply(remove_tags)


In [16]:
data['review'][1]

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [17]:
def lowercase(text):
  return text.lower()

In [18]:
data['review']=data['review'].apply(lowercase)

<ipython-input-18-096ca01d5e70>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['review']=data['review'].apply(lowercase)


In [19]:
data['review'][1]

'a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well done.'

In [20]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [21]:
y=lb.fit_transform(data['sentiment'])

In [22]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [23]:
y.shape

(9983,)

In [24]:
x=data['review']

In [25]:
x

0       one of the other reviewers has mentioned that ...
1       a wonderful little production. the filming tec...
2       i thought this was a wonderful way to spend ti...
3       basically there's a family where a little boy ...
4       petter mattei's "love in the time of money" is...
                              ...                        
9995    fun, entertaining movie about wwii german spy ...
9996    give me a break. how can anyone say that this ...
9997    this movie is a bad movie. but after watching ...
9998    this is a movie that was probably made to ente...
9999    smashing film about film-making. shows the int...
Name: review, Length: 9983, dtype: object

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [27]:
x_train.shape

(7986,)

In [28]:
# apply bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x_train_bow=cv.fit_transform(x_train).toarray()
x_test_bow=cv.transform(x_test).toarray()

In [29]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train_bow,y_train)

GaussianNB()

In [30]:
y_pred=gnb.predict(x_test_bow)
from sklearn.metrics import confusion_matrix,accuracy_score
accuracy_score(y_test,y_pred)

0.6364546820230346

In [31]:
confusion_matrix(y_test,y_pred)

array([[716, 236],
       [490, 555]])

In [32]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix
rf=RandomForestClassifier()
rf.fit(x_train_bow,y_train)
y_pred_rf=rf.predict(x_test_bow)
print(classification_report(y_test,y_pred_rf))
print(confusion_matrix(y_test,y_pred_rf))

              precision    recall  f1-score   support

           0       0.82      0.83      0.82       952
           1       0.85      0.83      0.84      1045

    accuracy                           0.83      1997
   macro avg       0.83      0.83      0.83      1997
weighted avg       0.83      0.83      0.83      1997

[[793 159]
 [178 867]]


In [ ]:
# using bigram

In [37]:
cv=CountVectorizer(ngram_range=(2,2))
x_train_ng=cv.fit_transform(x_train).toarray()
x_test_ng=cv.transform(x_test).toarray()

In [ ]:
rf=RandomForestClassifier()
rf.fit(x_train_ng,y_train)
y_pred_rf=rf.predict(x_test_ng)
print(classification_report(y_test,y_pred_rf))
print(confusion_matrix(y_test,y_pred_rf))

In [36]:
# using tf-idf
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
x_train_tf=tf.fit_transform(x_train).toarray()
x_test_tf=tf.transform(x_test).toarray()

In [37]:
rf=RandomForestClassifier()
rf.fit(x_train_tf,y_train)
y_pred_rf=rf.predict(x_test_tf)
print(classification_report(y_test,y_pred_rf))

              precision    recall  f1-score   support

           0       0.82      0.84      0.83       952
           1       0.85      0.83      0.84      1045

    accuracy                           0.84      1997
   macro avg       0.84      0.84      0.84      1997
weighted avg       0.84      0.84      0.84      1997



In [38]:
import gensim


In [41]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [42]:
story=[]
for doc in data['review']:
  raw_sent=sent_tokenize(doc)
  for sent in raw_sent:
    story.append(simple_preprocess(sent))

In [43]:
model = gensim.models.Word2Vec(window=10,min_count=2)
model.build_vocab( story)

In [44]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(8322303, 10950890)

In [48]:
import numpy as np

In [49]:
def document_vector(doc):
  doc=[word for word in doc.split() if word in model.wv.index_to_key]
  return np.mean(model.wv[doc],axis=0)

In [50]:
from tqdm import tqdm
X=[]
for doc in tqdm(data['review'].values):
  X.append(document_vector(doc))


100%|██████████| 9983/9983 [18:20<00:00,  9.07it/s]


In [51]:
X=np.array(X)

In [52]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)
mnb=GaussianNB()
mnb.fit(x_train,y_train)
y_pred=mnb.predict(x_test)
print(accuracy_score(y_test,y_pred))

0.6835252879318978


In [53]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred_rf=rf.predict(x_test)
print(classification_report(y_test,y_pred_rf))

              precision    recall  f1-score   support

           0       0.75      0.76      0.75       952
           1       0.78      0.77      0.77      1045

    accuracy                           0.76      1997
   macro avg       0.76      0.76      0.76      1997
weighted avg       0.76      0.76      0.76      1997

