<a href="https://colab.research.google.com/github/arun4589/ML/blob/main/Text_Representation_or_Featureextract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[0,1,1,1]})

total words contain in full dataset (repeated or non repeated ) is termed as corpus.
total non repeating words is called vocabulary .
every single review or 1 point in dataset is called document.


In [4]:
df

text  output
0   people watch campusx       0
1  campusx watch campusx       1
2   people write comment       1
3  campusx write comment       1

In [5]:
##1. Bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
bow=cv.fit_transform(df['text'])

In [8]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [9]:
print(bow[0].toarray())

[[1 0 1 1 0]]


In [11]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 1]])

In [17]:
##2. N-grams or bi/tri-grams
cv=CountVectorizer(ngram_range=(2,2))  #bigrams## change value of ngram range for bi/tri or other range gram

In [14]:
bigram=cv.fit_transform(df['text']).toarray()

In [15]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [16]:
print(bigram)


[[0 0 1 0 1 0]
 [1 0 0 0 1 0]
 [0 0 0 1 0 1]
 [0 1 0 0 0 1]]


In [18]:
##3. TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
tfidf=tf.fit_transform(df['text']).toarray()

In [19]:
print(tf.idf_)
print(tf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']


In [21]:
#4. WORD2VEC(most effective and used)
import gensim
from gensim.models import Word2Vec,KeyedVectors

In [22]:
!pip install wget

  Preparing metadata (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9656 sha256=bb4fc5cc883dff64fb2a4795620fd43b6a70880ef562f1e8269e8ce261f8e165
  Stored in directory: /root/.cache/pip/wheels/8b/f1/7f/5c94f0a7a505ca1c81cd1d9208ae2064675d97582078e6c769
Successfully built wget


In [25]:
!wget -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"

--2024-12-10 09:59:33--  https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.14.222, 16.15.184.139, 52.217.116.160, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.14.222|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-12-10 09:59:34 ERROR 404: Not Found.



In [ ]:
model=KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin.gz',binary=True)
# now by this model we can get word2vec form of every word

In [27]:
## training word2 vec model for got
import os

In [31]:
!pip install nltk
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [32]:
print(os.listdir('/content/'))

['.config', '001ssb.txt', '004ssb.txt', '005ssb.txt', '003ssb.txt', 'edit?resourcekey=0-wjGZdNAUop6WykTtMip30g', '002ssb.txt', 'sample_data']


In [34]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
story=[]
for filename in os.listdir('/content/'):
  if filename.endswith('.txt'):
    with open(filename,'r',encoding='latin-1') as f:
      file=f.read()
      sentences=sent_tokenize(file)
      for sent in sentences:
        words=simple_preprocess(sent)
        story.append(words)

In [36]:
len(story)

145020

In [37]:
model=gensim.models.Word2Vec(window=10,min_count=2)
model.build_vocab(story)

In [38]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(6569789, 8628190)

In [39]:
model.wv.most_similar('science')

[('fiction', 0.9883126020431519),
 ('copyright', 0.9620059728622437),
 ('com', 0.9591957330703735),
 ('tuf', 0.9565789699554443),
 ('publishers', 0.9549208283424377),
 ('sloey', 0.9543203711509705),
 ('allaquo', 0.9539945125579834),
 ('ling', 0.9518839120864868),
 ('nightflyers', 0.950124204158783),
 ('moredo', 0.9489490985870361)]

In [42]:
model.wv['com'].shape

(100,)

In [43]:
model.wv['king']

array([ 0.97513044, -0.94776475,  0.6991593 ,  2.5179772 , -1.9998858 ,
        1.0240872 , -0.13815151, -0.6659195 , -2.5100975 ,  0.3752867 ,
       -2.318271  ,  0.22842075, -1.1695378 ,  2.0508163 , -3.242327  ,
       -0.581699  , -1.0069965 ,  3.8938885 ,  0.5894961 ,  1.3451023 ,
        1.0344063 , -1.399477  ,  2.595052  , -0.9314924 , -0.7919088 ,
        1.543942  , -2.6683295 , -0.05326257,  0.20122655,  0.9221808 ,
       -1.918555  ,  0.00722385, -0.0646923 ,  0.11873403,  1.2535837 ,
       -3.6536357 , -2.253604  ,  0.15268546, -0.5258298 , -2.2294812 ,
        0.34407791,  2.901925  ,  3.1816876 ,  0.9102254 , -0.8290923 ,
       -1.4913262 , -1.0135659 , -3.5071945 ,  2.2068393 , -4.489543  ,
       -2.511513  , -1.1335422 , -3.1612978 , -2.072013  ,  3.07207   ,
       -2.6109784 ,  2.1855307 ,  0.50672007,  0.3857935 ,  0.8101244 ,
        1.8650204 , -0.13546704, -1.7024288 ,  1.643207  ,  0.77935535,
        2.6945868 ,  0.30691817, -0.5853102 , -1.5605525 , -0.94

In [48]:
story[0]

['game',
 'of',
 'thrones',
 'book',
 'one',
 'of',
 'song',
 'of',
 'ice',
 'and',
 'fire',
 'by',
 'george',
 'martin',
 'prologue',
 'we',
 'should',
 'start',
 'back',
 'gared',
 'urged',
 'as',
 'the',
 'woods',
 'began',
 'to',
 'grow',
 'dark',
 'around',
 'them']

In [49]:
from sklearn.decomposition import PCA
pca=PCA(n_components=3)

In [50]:
x=pca.fit_transform(model.wv.get_normed_vectors())

In [51]:
y=model.wv.index_to_key

In [53]:
import plotly.express as px
fig=px.scatter_3d(x[:500],x=0,y=1,z=2,color=y[:500])
fig.show()